### ISSUE TITLE
websocket transport

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiosockjs#2]
websocket transport doesnt work with browser, while it passes sockjs-protocol-dev.py tests

**Comment by jettify** [comment]
I guess issue is here:
https://github.com/aio-libs/aiosockjs/blob/master/sockjs/transports/websocket.py#L12-L15

web socket transport is working for me in chat demo if i substitute:
``self.ws.send_bytes(b'o')``
with
``self.ws.send_str('o')``

**Comment by fafhrd91** [comment]
oh! cool. thanks
